% ----------------------------------------------------------------------------
\subsection{Mười bộ dữ liệu chuẩn}\label{sec:bench10}

\paragraph{Dữ liệu và giao thức.} Đề án dùng mười bộ dữ liệu phân loại nhị phân (\cref{tab:datasets}). Bảy bộ trong số đó có mặt trong Bảng~1 của bài báo gốc (Haberman, Transfusion, Pima, Breast, Magic, Parkinsons, Ionosphere); ba bộ còn lại (Banknote, Spambase, Sonar) được thêm vào để bao quát thêm các kích thước dữ liệu và số chiều khác nhau. Mỗi bộ được chia ngẫu nhiên có phân tầng thành hai nửa huấn luyện và kiểm tra, lặp lại $10$ lần; với Magic, tập huấn luyện gồm $2.000$ điểm như trong bài báo gốc, phần còn lại dùng để kiểm tra; với Spambase, do chi phí tinh chỉnh các mô hình hạt nhân lớn, chỉ lặp lại $5$ lần. Trên mỗi tập huấn luyện, tham số được chọn bằng kiểm định chéo $10$ phần: $\gamma\in\{2^{-5},2^{-3},\dots,2^{11}\}$ cho mọi mô hình SVM, tham số $1/\sigma^2$ của hạt nhân Gauss trên lưới $\{2^{-15},2^{-13},\dots,2^{3}\}$ theo khuyến nghị của~\cite{hsu2003}, và hệ số phạt $L_2$ của mạng nơ-ron trong $\{10^{-4},10^{-3},\dots,1\}$. Chín phương pháp được so sánh: SVM tuyến tính; SVM và LS-SVM hạt nhân Gauss; kNN với $k=1$ như trong bài báo; Ik-SVM; mạng nơ-ron một lớp ẩn gồm $D=9n$ nơ-ron ReLU, bằng đúng số đặc trưng bản lề của PWL-SVM dạng HH, được huấn luyện bằng L-BFGS~\cite{liu1989}; và ba biến thể PWL-SVM với $M/n=10$ theo đúng quy tắc của bài báo: PWL-C-SVM và PWL-LS-SVM với ánh xạ cộng tính lưới đều, và PWL-C-SVM với ánh xạ HH chuẩn hóa $|p(1)|=1$.

\input{chapters/tab_datasets}

\input{chapters/tab_bench}

\paragraph{Kết quả tổng quát.} \Cref{tab:bench} cho độ chính xác trung bình và \cref{fig:bench-diff} biểu diễn chênh lệch so với SVM hạt nhân Gauss; độ lệch chuẩn và kích thước mô hình được cho ở Phụ lục~B. Ba phương pháp dẫn đầu về độ chính xác là {{TOP3_TEXT}}. PWL-C-SVM cộng tính đứng giữa bảng (hạng ${{R_PWLC}}$), trên SVM tuyến tính (${{R_LIN}}$) và kNN (${{R_KNN}}$).

Bức tranh rõ hơn khi tách các bộ dữ liệu thành hai nhóm. Ở nhóm thứ nhất gồm Haberman, Transfusion, Banknote, Pima và Breast, mọi phương pháp dựa trên SVM, kể cả SVM tuyến tính, chênh nhau không quá khoảng $1{,}5$ điểm phần trăm: một biên tuyến tính đã gần như đủ tốt, và tính phi tuyến không đem lại lợi ích đáng kể. Ở nhóm thứ hai gồm Magic, Parkinsons, Ionosphere, Sonar, nơi SVM tuyến tính kém SVM hạt nhân Gauss từ $4$ đến $9$ điểm, PWL-C-SVM cộng tính thu hẹp đáng kể khoảng cách trên ba trong bốn bộ: nó cải thiện so với SVM tuyến tính $5{,}8$ điểm trên Magic, $3{,}5$ điểm trên Ionosphere và $5{,}0$ điểm trên Sonar, nhưng vẫn kém SVM hạt nhân Gauss từ $0{,}7$ đến $4{,}1$ điểm. Magic là trường hợp đáng chú ý nhất: PWL-C-SVM đạt ${{MAGIC_C}}\%$ so với ${{MAGIC_RBF}}\%$ của SVM hạt nhân Gauss, trong khi mô hình chỉ gồm ${{P_C_MAGIC}}$ số thực so với ${{P_RBF_MAGIC}}$ số, nhỏ hơn khoảng ${{RATIO_MAGIC}}$ lần.

\begin{figure}[t]
\centering
\includegraphics[width=\linewidth]{fig_benchmark_diff.pdf}
\caption[Chênh lệch độ chính xác so với SVM hạt nhân Gauss]{Chênh lệch độ chính xác trung bình so với SVM hạt nhân Gauss (điểm phần trăm; giá trị âm nghĩa là kém hơn) của bốn phương pháp trên mười bộ dữ liệu.{{BENCH_DIFF_NOTE}}}
\label{fig:bench-diff}
\end{figure}

\input{chapters/tab_wilcoxon}

\paragraph{Kiểm định thống kê.} \Cref{tab:wilcoxon} so sánh PWL-C-SVM cộng tính với từng phương pháp bằng kiểm định dấu hạng Wilcoxon trên mười cặp giá trị trung bình, theo khuyến nghị của Demšar~\cite{demsar2006}. {{WILCOX_TEXT}} Với chỉ mười bộ dữ liệu, các kiểm định này có lực thấp, nên “không bác bỏ” không có nghĩa là “tương đương”.

\paragraph{Ánh xạ HH và quy tắc chọn tham số.} PWL-C-SVM với ánh xạ HH có hạng trung bình thấp (${{R_HH}}$), và trên Spambase kết quả của nó rất bất ổn: {{HH_SPAM_SENT}}. Nguyên nhân nằm ở quy tắc sinh tham số chứ không ở mô hình. Dữ liệu Spambase rất thưa: sau khi chuẩn hóa, gần $78\%$ các giá trị bằng $0$, và phần lớn dữ liệu nằm sát một đỉnh của hình hộp $[0,1]^{57}$. Các siêu phẳng đi qua những điểm lấy đều trong hình hộp vì vậy thường không cắt qua vùng dữ liệu: ở mỗi lần chia, từ {{DEAD_MIN}} đến {{DEAD_MAX}} số đặc trưng bản lề bằng $0$ trên mọi điểm huấn luyện, và từ {{ALW_MIN}} đến {{ALW_MAX}} luôn hoạt động, tức là chỉ tuyến tính trên dữ liệu. Nghiêm trọng hơn, việc cố định $|p(1)|=1$ (\cref{rem:scale}) làm độ lớn của các đặc trưng phụ thuộc mạnh vào lần sinh ngẫu nhiên: giá trị lớn nhất của các đặc trưng trên tập huấn luyện dao động từ ${{MAXH_MIN}}$ đến ${{MAXH_MAX}}$ giữa các lần chia. Ở lần chia đầu tiên, một siêu phẳng gần song song với trục $x(1)$ có hệ số lên tới ${{MAXP0}}$, khiến bài toán tối ưu bị điều kiện hóa rất kém và bộ giải LIBLINEAR không hội tụ tới một nghiệm có ý nghĩa. Chỉ cần chuẩn hóa $\|p\|_2=1$, các đặc trưng trên dữ liệu huấn luyện không vượt quá ${{NORM_MAXH}}$ ở mọi lần chia, và với cùng giao thức, PWL-C-SVM HH đạt {{SPAMHHNORM}} trên Spambase. Nhìn chung, mạng nơ-ron với cùng số nơ-ron ẩn tốt hơn PWL-C-SVM HH trên {{N_MLP_HH}} trong mười bộ: học lớp ẩn từ dữ liệu có lợi hơn nhiều so với sinh nó ngẫu nhiên, và đó là cái giá của tính lồi đã được nêu ở Mục~\ref{sec:pwlsvm}.

\paragraph{So với bài báo gốc.} Kết quả trên không xác nhận nhận định của bài báo gốc rằng PWL-SVM có độ chính xác tương đương SVM hạt nhân Gauss~\cite{huang2013}. Nguyên nhân chính là bài báo chỉ dùng một lần chia dữ liệu: trên các bộ nhỏ như Parkinsons, với $98$ điểm kiểm tra, độ lệch chuẩn giữa các lần chia lên tới $2$--$4$ điểm phần trăm, nên một lần chia có thể cho kết quả rất lạc quan; bài báo báo cáo độ chính xác $100\%$ cho PWL-C-SVM trên bộ này, trong khi trung bình qua mười lần chia là $86{,}2\%$. Mặt khác, lợi thế về kích thước mô hình được xác nhận rõ ràng: với ánh xạ cộng tính, PWL-C-SVM cần từ ${{PWLC_PMIN}}$ đến ${{PWLC_PMAX}}$ số thực, nhỏ hơn SVM hạt nhân Gauss từ ${{RATIO_MIN}}$ đến ${{RATIO_MAX}}$ lần trên cả mười bộ dữ liệu (Phụ lục~B).

% ----------------------------------------------------------------------------
\subsection{Ảnh hưởng của số đặc trưng và của quy tắc chọn tham số}\label{sec:sensitivity}

Để trả lời câu hỏi CH3 một cách có kiểm soát, ta cố định mô hình là PWL-LS-SVM, giải chính xác bằng hồi quy ridge (\cref{prop:ridge}) để loại trừ ảnh hưởng của bộ giải, và thay đổi hai yếu tố: số đặc trưng trên mỗi chiều $M/n\in\{1,2,3,5,10,20\}$ và quy tắc chọn tham số. Bốn quy tắc được so sánh: ánh xạ cộng tính với lưới đều (quy tắc của bài báo gốc) và với lưới phân vị (\cref{rem:quantile}); ánh xạ HH với $|p(1)|=1$ (quy tắc của bài báo gốc) và với $\|p\|_2=1$ (\cref{rem:scale}). Thí nghiệm được thực hiện trên ba bộ dữ liệu có đặc điểm khác nhau --- Ionosphere ($n=33$), Magic ($n=10$, nhiều dữ liệu) và Spambase ($n=57$, rất thưa) --- với $5$ lần chia như ở Mục~\ref{sec:bench10} và $\gamma$ chọn bằng kiểm định chéo $5$ phần. Kết quả được vẽ ở \cref{fig:sensitivity}.

\begin{figure}[t]
\centering
\includegraphics[width=\linewidth]{fig_sensitivity.pdf}
\caption[Ảnh hưởng của số đặc trưng và quy tắc chọn tham số]{Độ chính xác trung bình (qua $5$ lần chia) của PWL-LS-SVM theo số đặc trưng trên mỗi chiều $M/n$, với bốn quy tắc chọn tham số. $M/n=1$ ứng với bộ phân loại tuyến tính.}
\label{fig:sensitivity}
\end{figure}

Có bốn nhận xét. Thứ nhất, độ chính xác tăng nhanh khi $M/n$ tăng từ $1$ (bộ phân loại tuyến tính) và bão hòa quanh $M/n=5$--$10$, phù hợp với quy tắc $M=10n$ của bài báo gốc; tăng tiếp lên $M/n=20$ hầu như không có lợi. Thứ hai, đặt nút theo phân vị cho kết quả tốt hơn hoặc ngang lưới đều trên cả ba bộ dữ liệu, và khác biệt rõ nhất trên những dữ liệu có phân bố lệch: trên Magic, lưới phân vị đạt $84{,}2\%$ ngay với $M/n=2$, trong khi lưới đều cần $M/n=10$ để đạt $84{,}3\%$; trên Spambase, lưới phân vị đạt $93{,}9\%$ so với $92{,}6\%$ của lưới đều ở $M/n=10$, đồng thời chỉ dùng $156$ đặc trưng thay vì $570$, vì các nút trùng nhau của những biến gần như luôn bằng $0$ bị loại bỏ. Thứ ba, ánh xạ HH cần nhiều đặc trưng hơn hẳn mới đạt tới độ chính xác của ánh xạ cộng tính: trên Magic, nó chỉ đuổi kịp lưới phân vị khi $M/n\ge10$ (và nhỉnh hơn $0{,}4$ điểm ở $M/n=20$), còn trên Spambase nó kém ở mọi giá trị của $M/n$; chỉ trên Ionosphere, nơi tương tác giữa các biến có vai trò, HH với $\|p\|_2=1$ đạt kết quả tốt nhất ($90{,}0\%$ ở $M/n=10$). Thứ tư, chuẩn hóa $\|p\|_2=1$ không bao giờ làm kết quả xấu đi đáng kể và cải thiện rõ trên Ionosphere ($90{,}0\%$ so với $86{,}9\%$ ở $M/n=10$); kết hợp với sự cố của LIBLINEAR trên Spambase, đây là một lý do mạnh để thay quy tắc $|p(1)|=1$ bằng $\|p\|_2=1$.

Từ đó rút ra một quy trình thực hành cho dữ liệu dạng bảng: bắt đầu với ánh xạ cộng tính, nút theo phân vị và $M/n$ khoảng $5$ đến $10$; chỉ dùng ánh xạ HH, với các siêu phẳng được chuẩn hóa, khi có dấu hiệu tương tác mạnh giữa các biến. Quy trình này được áp dụng cho bài toán tín dụng ở Mục~\ref{sec:application}.
